/* YaHa — HSK1 vocabulary, survival phrases, and mini dialogues.
   Plain script (no modules). Assigns window.YAHA_DATA. */

window.YAHA_DATA = {

vocab: [
  { hanzi: "我", pinyin: "wǒ", en: "I, me", pos: "pron", cat: "people" },
  { hanzi: "我们", pinyin: "wǒmen", en: "we, us", pos: "pron", cat: "people" },
  { hanzi: "你", pinyin: "nǐ", en: "you", pos: "pron", cat: "people" },
  { hanzi: "他", pinyin: "tā", en: "he, him", pos: "pron", cat: "people" },
  { hanzi: "她", pinyin: "tā", en: "she, her", pos: "pron", cat: "people" },
  { hanzi: "这", pinyin: "zhè", en: "this", pos: "pron", cat: "grammar" },
  { hanzi: "那", pinyin: "nà", en: "that", pos: "pron", cat: "grammar" },
  { hanzi: "哪", pinyin: "nǎ", en: "which", pos: "question", cat: "question" },
  { hanzi: "哪儿", pinyin: "nǎr", en: "where", pos: "question", cat: "question" },
  { hanzi: "谁", pinyin: "shéi", en: "who", pos: "question", cat: "question" },
  { hanzi: "什么", pinyin: "shénme", en: "what", pos: "question", cat: "question" },
  { hanzi: "多少", pinyin: "duōshao", en: "how many, how much", pos: "question", cat: "question" },
  { hanzi: "几", pinyin: "jǐ", en: "how many (small numbers)", pos: "question", cat: "question" },
  { hanzi: "怎么", pinyin: "zěnme", en: "how", pos: "question", cat: "question" },
  { hanzi: "怎么样", pinyin: "zěnmeyàng", en: "how about, how is it", pos: "question", cat: "question" },
  { hanzi: "一", pinyin: "yī", en: "one", pos: "num", cat: "numbers" },
  { hanzi: "二", pinyin: "èr", en: "two", pos: "num", cat: "numbers" },
  { hanzi: "三", pinyin: "sān", en: "three", pos: "num", cat: "numbers" },
  { hanzi: "四", pinyin: "sì", en: "four", pos: "num", cat: "numbers" },
  { hanzi: "五", pinyin: "wǔ", en: "five", pos: "num", cat: "numbers" },
  { hanzi: "六", pinyin: "liù", en: "six", pos: "num", cat: "numbers" },
  { hanzi: "七", pinyin: "qī", en: "seven", pos: "num", cat: "numbers" },
  { hanzi: "八", pinyin: "bā", en: "eight", pos: "num", cat: "numbers" },
  { hanzi: "九", pinyin: "jiǔ", en: "nine", pos: "num", cat: "numbers" },
  { hanzi: "十", pinyin: "shí", en: "ten", pos: "num", cat: "numbers" },
  { hanzi: "个", pinyin: "gè", en: "measure word (general)", pos: "measure", cat: "grammar" },
  { hanzi: "岁", pinyin: "suì", en: "years old", pos: "measure", cat: "grammar" },
  { hanzi: "本", pinyin: "běn", en: "measure word (for books)", pos: "measure", cat: "grammar" },
  { hanzi: "些", pinyin: "xiē", en: "some", pos: "measure", cat: "grammar" },
  { hanzi: "块", pinyin: "kuài", en: "measure word (money, piece)", pos: "measure", cat: "grammar" },
  { hanzi: "不", pinyin: "bù", en: "not, no", pos: "adv", cat: "grammar" },
  { hanzi: "没", pinyin: "méi", en: "not, have not", pos: "adv", cat: "grammar" },
  { hanzi: "很", pinyin: "hěn", en: "very", pos: "adv", cat: "grammar" },
  { hanzi: "太", pinyin: "tài", en: "too, extremely", pos: "adv", cat: "grammar" },
  { hanzi: "都", pinyin: "dōu", en: "all, both", pos: "adv", cat: "grammar" },
  { hanzi: "一点儿", pinyin: "yìdiǎnr", en: "a little bit", pos: "adv", cat: "grammar" },
  { hanzi: "和", pinyin: "hé", en: "and", pos: "conj", cat: "grammar" },
  { hanzi: "在", pinyin: "zài", en: "at, in; to be located at", pos: "v", cat: "grammar" },
  { hanzi: "的", pinyin: "de", en: "possessive particle", pos: "particle", cat: "grammar" },
  { hanzi: "了", pinyin: "le", en: "completed-action particle", pos: "particle", cat: "grammar" },
  { hanzi: "吗", pinyin: "ma", en: "question particle", pos: "particle", cat: "question" },
  { hanzi: "呢", pinyin: "ne", en: "question particle", pos: "particle", cat: "question" },
  { hanzi: "喂", pinyin: "wèi", en: "hello (on the phone)", pos: "greeting", cat: "greetings" },
  { hanzi: "家", pinyin: "jiā", en: "home, family", pos: "n", cat: "places" },
  { hanzi: "学校", pinyin: "xuéxiào", en: "school", pos: "n", cat: "places" },
  { hanzi: "饭店", pinyin: "fàndiàn", en: "restaurant, hotel", pos: "n", cat: "places" },
  { hanzi: "商店", pinyin: "shāngdiàn", en: "shop, store", pos: "n", cat: "places" },
  { hanzi: "医院", pinyin: "yīyuàn", en: "hospital", pos: "n", cat: "places" },
  { hanzi: "中国", pinyin: "Zhōngguó", en: "China", pos: "n", cat: "places" },
  { hanzi: "北京", pinyin: "Běijīng", en: "Beijing", pos: "n", cat: "places" },
  { hanzi: "上", pinyin: "shàng", en: "on, above, up", pos: "n", cat: "places" },
  { hanzi: "下", pinyin: "xià", en: "below, down", pos: "n", cat: "places" },
  { hanzi: "前面", pinyin: "qiánmiàn", en: "front", pos: "n", cat: "places" },
  { hanzi: "后面", pinyin: "hòumiàn", en: "behind", pos: "n", cat: "places" },
  { hanzi: "里面", pinyin: "lǐmiàn", en: "inside", pos: "n", cat: "places" },
  { hanzi: "今天", pinyin: "jīntiān", en: "today", pos: "n", cat: "time" },
  { hanzi: "明天", pinyin: "míngtiān", en: "tomorrow", pos: "n", cat: "time" },
  { hanzi: "昨天", pinyin: "zuótiān", en: "yesterday", pos: "n", cat: "time" },
  { hanzi: "上午", pinyin: "shàngwǔ", en: "morning", pos: "n", cat: "time" },
  { hanzi: "中午", pinyin: "zhōngwǔ", en: "noon", pos: "n", cat: "time" },
  { hanzi: "下午", pinyin: "xiàwǔ", en: "afternoon", pos: "n", cat: "time" },
  { hanzi: "年", pinyin: "nián", en: "year", pos: "n", cat: "time" },
  { hanzi: "月", pinyin: "yuè", en: "month", pos: "n", cat: "time" },
  { hanzi: "号", pinyin: "hào", en: "date, number", pos: "n", cat: "time" },
  { hanzi: "星期", pinyin: "xīngqī", en: "week", pos: "n", cat: "time" },
  { hanzi: "点", pinyin: "diǎn", en: "o'clock", pos: "n", cat: "time" },
  { hanzi: "分钟", pinyin: "fēnzhōng", en: "minute", pos: "n", cat: "time" },
  { hanzi: "现在", pinyin: "xiànzài", en: "now", pos: "n", cat: "time" },
  { hanzi: "时候", pinyin: "shíhou", en: "time, moment", pos: "n", cat: "time" },
  { hanzi: "爸爸", pinyin: "bàba", en: "dad", pos: "n", cat: "people" },
  { hanzi: "妈妈", pinyin: "māma", en: "mom", pos: "n", cat: "people" },
  { hanzi: "儿子", pinyin: "érzi", en: "son", pos: "n", cat: "people" },
  { hanzi: "女儿", pinyin: "nǚ'ér", en: "daughter", pos: "n", cat: "people" },
  { hanzi: "老师", pinyin: "lǎoshī", en: "teacher", pos: "n", cat: "people" },
  { hanzi: "学生", pinyin: "xuésheng", en: "student", pos: "n", cat: "people" },
  { hanzi: "同学", pinyin: "tóngxué", en: "classmate", pos: "n", cat: "people" },
  { hanzi: "朋友", pinyin: "péngyou", en: "friend", pos: "n", cat: "people" },
  { hanzi: "医生", pinyin: "yīshēng", en: "doctor", pos: "n", cat: "people" },
  { hanzi: "先生", pinyin: "xiānsheng", en: "Mr., sir", pos: "n", cat: "people" },
  { hanzi: "小姐", pinyin: "xiǎojiě", en: "Miss", pos: "n", cat: "people" },
  { hanzi: "衣服", pinyin: "yīfu", en: "clothes", pos: "n", cat: "objects" },
  { hanzi: "水", pinyin: "shuǐ", en: "water", pos: "n", cat: "food" },
  { hanzi: "菜", pinyin: "cài", en: "dish, vegetable", pos: "n", cat: "food" },
  { hanzi: "米饭", pinyin: "mǐfàn", en: "rice", pos: "n", cat: "food" },
  { hanzi: "水果", pinyin: "shuǐguǒ", en: "fruit", pos: "n", cat: "food" },
  { hanzi: "苹果", pinyin: "píngguǒ", en: "apple", pos: "n", cat: "food" },
  { hanzi: "茶", pinyin: "chá", en: "tea", pos: "n", cat: "food" },
  { hanzi: "杯子", pinyin: "bēizi", en: "cup", pos: "n", cat: "objects" },
  { hanzi: "钱", pinyin: "qián", en: "money", pos: "n", cat: "objects" },
  { hanzi: "飞机", pinyin: "fēijī", en: "airplane", pos: "n", cat: "travel" },
  { hanzi: "出租车", pinyin: "chūzūchē", en: "taxi", pos: "n", cat: "travel" },
  { hanzi: "电视", pinyin: "diànshì", en: "television", pos: "n", cat: "objects" },
  { hanzi: "电脑", pinyin: "diànnǎo", en: "computer", pos: "n", cat: "objects" },
  { hanzi: "电影", pinyin: "diànyǐng", en: "movie", pos: "n", cat: "objects" },
  { hanzi: "天气", pinyin: "tiānqì", en: "weather", pos: "n", cat: "objects" },
  { hanzi: "猫", pinyin: "māo", en: "cat", pos: "n", cat: "objects" },
  { hanzi: "狗", pinyin: "gǒu", en: "dog", pos: "n", cat: "objects" },
  { hanzi: "东西", pinyin: "dōngxi", en: "thing", pos: "n", cat: "objects" },
  { hanzi: "人", pinyin: "rén", en: "person", pos: "n", cat: "people" },
  { hanzi: "名字", pinyin: "míngzi", en: "name", pos: "n", cat: "people" },
  { hanzi: "书", pinyin: "shū", en: "book", pos: "n", cat: "objects" },
  { hanzi: "汉语", pinyin: "Hànyǔ", en: "Chinese language", pos: "n", cat: "objects" },
  { hanzi: "字", pinyin: "zì", en: "character", pos: "n", cat: "objects" },
  { hanzi: "桌子", pinyin: "zhuōzi", en: "table, desk", pos: "n", cat: "objects" },
  { hanzi: "椅子", pinyin: "yǐzi", en: "chair", pos: "n", cat: "objects" },
  { hanzi: "谢谢", pinyin: "xièxie", en: "thank you", pos: "greeting", cat: "greetings" },
  { hanzi: "不客气", pinyin: "bú kèqi", en: "you're welcome", pos: "greeting", cat: "greetings" },
  { hanzi: "再见", pinyin: "zàijiàn", en: "goodbye", pos: "greeting", cat: "greetings" },
  { hanzi: "请", pinyin: "qǐng", en: "please", pos: "v", cat: "greetings" },
  { hanzi: "对不起", pinyin: "duìbuqǐ", en: "sorry", pos: "greeting", cat: "greetings" },
  { hanzi: "没关系", pinyin: "méi guānxi", en: "it's okay, never mind", pos: "greeting", cat: "greetings" },
  { hanzi: "是", pinyin: "shì", en: "to be (am, is, are)", pos: "v", cat: "verbs" },
  { hanzi: "有", pinyin: "yǒu", en: "to have", pos: "v", cat: "verbs" },
  { hanzi: "看", pinyin: "kàn", en: "to look, to read, to watch", pos: "v", cat: "verbs" },
  { hanzi: "听", pinyin: "tīng", en: "to listen", pos: "v", cat: "verbs" },
  { hanzi: "说", pinyin: "shuō", en: "to speak", pos: "v", cat: "verbs" },
  { hanzi: "读", pinyin: "dú", en: "to read aloud", pos: "v", cat: "verbs" },
  { hanzi: "写", pinyin: "xiě", en: "to write", pos: "v", cat: "verbs" },
  { hanzi: "看见", pinyin: "kànjiàn", en: "to see", pos: "v", cat: "verbs" },
  { hanzi: "叫", pinyin: "jiào", en: "to be called, to call", pos: "v", cat: "verbs" },
  { hanzi: "来", pinyin: "lái", en: "to come", pos: "v", cat: "verbs" },
  { hanzi: "回", pinyin: "huí", en: "to return", pos: "v", cat: "verbs" },
  { hanzi: "去", pinyin: "qù", en: "to go", pos: "v", cat: "verbs" },
  { hanzi: "吃", pinyin: "chī", en: "to eat", pos: "v", cat: "verbs" },
  { hanzi: "喝", pinyin: "hē", en: "to drink", pos: "v", cat: "verbs" },
  { hanzi: "睡觉", pinyin: "shuìjiào", en: "to sleep", pos: "v", cat: "verbs" },
  { hanzi: "打电话", pinyin: "dǎ diànhuà", en: "to make a phone call", pos: "v", cat: "verbs" },
  { hanzi: "做", pinyin: "zuò", en: "to do, to make", pos: "v", cat: "verbs" },
  { hanzi: "买", pinyin: "mǎi", en: "to buy", pos: "v", cat: "verbs" },
  { hanzi: "开", pinyin: "kāi", en: "to open, to drive", pos: "v", cat: "verbs" },
  { hanzi: "坐", pinyin: "zuò", en: "to sit, to take (transport)", pos: "v", cat: "travel" },
  { hanzi: "住", pinyin: "zhù", en: "to live, to stay", pos: "v", cat: "verbs" },
  { hanzi: "学习", pinyin: "xuéxí", en: "to study", pos: "v", cat: "verbs" },
  { hanzi: "工作", pinyin: "gōngzuò", en: "to work; job", pos: "v", cat: "verbs" },
  { hanzi: "下雨", pinyin: "xiàyǔ", en: "to rain", pos: "v", cat: "verbs" },
  { hanzi: "爱", pinyin: "ài", en: "to love", pos: "v", cat: "verbs" },
  { hanzi: "喜欢", pinyin: "xǐhuan", en: "to like", pos: "v", cat: "verbs" },
  { hanzi: "想", pinyin: "xiǎng", en: "to want to, to think", pos: "v", cat: "verbs" },
  { hanzi: "认识", pinyin: "rènshi", en: "to know (a person)", pos: "v", cat: "verbs" },
  { hanzi: "会", pinyin: "huì", en: "can, know how to", pos: "v", cat: "verbs" },
  { hanzi: "能", pinyin: "néng", en: "can, to be able to", pos: "v", cat: "verbs" },
  { hanzi: "好", pinyin: "hǎo", en: "good", pos: "adj", cat: "adjectives" },
  { hanzi: "大", pinyin: "dà", en: "big", pos: "adj", cat: "adjectives" },
  { hanzi: "小", pinyin: "xiǎo", en: "small", pos: "adj", cat: "adjectives" },
  { hanzi: "多", pinyin: "duō", en: "many, much", pos: "adj", cat: "adjectives" },
  { hanzi: "少", pinyin: "shǎo", en: "few, little", pos: "adj", cat: "adjectives" },
  { hanzi: "冷", pinyin: "lěng", en: "cold", pos: "adj", cat: "adjectives" },
  { hanzi: "热", pinyin: "rè", en: "hot", pos: "adj", cat: "adjectives" },
  { hanzi: "高兴", pinyin: "gāoxìng", en: "happy", pos: "adj", cat: "adjectives" },
  { hanzi: "漂亮", pinyin: "piàoliang", en: "pretty, beautiful", pos: "adj", cat: "adjectives" }
],

phrases: [
  // greetings
  { hanzi: "你好", pinyin: "nǐ hǎo", en: "hello", scenario: "greetings", note: "most common all-purpose greeting" },
  { hanzi: "你好吗？", pinyin: "nǐ hǎo ma?", en: "how are you?", scenario: "greetings", note: "" },
  { hanzi: "我很好", pinyin: "wǒ hěn hǎo", en: "I'm fine", scenario: "greetings", note: "typical reply to 你好吗" },
  { hanzi: "谢谢", pinyin: "xièxie", en: "thank you", scenario: "greetings", note: "" },
  { hanzi: "不客气", pinyin: "bú kèqi", en: "you're welcome", scenario: "greetings", note: "" },
  { hanzi: "再见", pinyin: "zàijiàn", en: "goodbye", scenario: "greetings", note: "" },
  { hanzi: "对不起", pinyin: "duìbuqǐ", en: "sorry, excuse me", scenario: "greetings", note: "also used to get attention politely" },

  // restaurant
  { hanzi: "我要这个", pinyin: "wǒ yào zhège", en: "I want this one", scenario: "restaurant", note: "point at the menu while saying it" },
  { hanzi: "请给我菜单", pinyin: "qǐng gěi wǒ càidān", en: "please give me the menu", scenario: "restaurant", note: "" },
  { hanzi: "我要一杯茶", pinyin: "wǒ yào yì bēi chá", en: "I'd like a cup of tea", scenario: "restaurant", note: "swap 茶 for other drinks" },
  { hanzi: "好吃吗？", pinyin: "hǎochī ma?", en: "is it tasty?", scenario: "restaurant", note: "" },
  { hanzi: "买单", pinyin: "mǎidān", en: "check, please", scenario: "restaurant", note: "say it or just raise a hand and mime signing" },
  { hanzi: "我不吃辣", pinyin: "wǒ bù chī là", en: "I don't eat spicy food", scenario: "restaurant", note: "" },
  { hanzi: "有没有米饭？", pinyin: "yǒu méiyǒu mǐfàn?", en: "do you have rice?", scenario: "restaurant", note: "有没有 = do you have (yes/no pattern)" },

  // shopping
  { hanzi: "多少钱？", pinyin: "duōshao qián?", en: "how much is it?", scenario: "shopping", note: "" },
  { hanzi: "太贵了", pinyin: "tài guì le", en: "too expensive", scenario: "shopping", note: "" },
  { hanzi: "便宜一点儿", pinyin: "piányi yìdiǎnr", en: "a little cheaper", scenario: "shopping", note: "for gentle bargaining" },
  { hanzi: "我要买这个", pinyin: "wǒ yào mǎi zhège", en: "I want to buy this", scenario: "shopping", note: "" },
  { hanzi: "可以刷卡吗？", pinyin: "kěyǐ shuākǎ ma?", en: "can I pay by card?", scenario: "shopping", note: "" },
  { hanzi: "我只是看看", pinyin: "wǒ zhǐshì kànkan", en: "I'm just looking", scenario: "shopping", note: "polite way to browse without buying" },
  { hanzi: "有别的颜色吗？", pinyin: "yǒu bié de yánsè ma?", en: "do you have other colors?", scenario: "shopping", note: "" },

  // transport
  { hanzi: "我要去机场", pinyin: "wǒ yào qù jīchǎng", en: "I want to go to the airport", scenario: "transport", note: "swap 机场 for any destination" },
  { hanzi: "出租车站在哪儿？", pinyin: "chūzūchē zhàn zài nǎr?", en: "where's the taxi stand?", scenario: "transport", note: "" },
  { hanzi: "请等一下", pinyin: "qǐng děng yíxià", en: "please wait a moment", scenario: "transport", note: "" },
  { hanzi: "这是几路车？", pinyin: "zhè shì jǐ lù chē?", en: "what bus number is this?", scenario: "transport", note: "" },
  { hanzi: "到火车站要多久？", pinyin: "dào huǒchēzhàn yào duō jiǔ?", en: "how long to the train station?", scenario: "transport", note: "" },
  { hanzi: "请开慢一点儿", pinyin: "qǐng kāi màn yìdiǎnr", en: "please drive a bit slower", scenario: "transport", note: "" },
  { hanzi: "地铁站在哪儿？", pinyin: "dìtiě zhàn zài nǎr?", en: "where's the subway station?", scenario: "transport", note: "" },

  // hotel
  { hanzi: "我订了一个房间", pinyin: "wǒ dìng le yí gè fángjiān", en: "I booked a room", scenario: "hotel", note: "" },
  { hanzi: "我要退房", pinyin: "wǒ yào tuì fáng", en: "I want to check out", scenario: "hotel", note: "" },
  { hanzi: "有没有网络？", pinyin: "yǒu méiyǒu wǎngluò?", en: "is there wifi?", scenario: "hotel", note: "" },
  { hanzi: "密码是什么？", pinyin: "mìmǎ shì shénme?", en: "what's the password?", scenario: "hotel", note: "for wifi" },
  { hanzi: "房间里有没有热水？", pinyin: "fángjiān lǐ yǒu méiyǒu rè shuǐ?", en: "is there hot water in the room?", scenario: "hotel", note: "" },
  { hanzi: "几点可以入住？", pinyin: "jǐ diǎn kěyǐ rùzhù?", en: "what time can I check in?", scenario: "hotel", note: "" },
  { hanzi: "请给我一个大一点儿的房间", pinyin: "qǐng gěi wǒ yí gè dà yìdiǎnr de fángjiān", en: "please give me a bigger room", scenario: "hotel", note: "" },

  // directions
  { hanzi: "洗手间在哪儿？", pinyin: "xǐshǒujiān zài nǎr?", en: "where's the restroom?", scenario: "directions", note: "essential travel phrase" },
  { hanzi: "请问，这是哪儿？", pinyin: "qǐngwèn, zhè shì nǎr?", en: "excuse me, where is this?", scenario: "directions", note: "请问 politely opens a question" },
  { hanzi: "一直走", pinyin: "yìzhí zǒu", en: "go straight", scenario: "directions", note: "" },
  { hanzi: "往左边走", pinyin: "wǎng zuǒbiān zǒu", en: "go left", scenario: "directions", note: "" },
  { hanzi: "往右边走", pinyin: "wǎng yòubiān zǒu", en: "go right", scenario: "directions", note: "" },
  { hanzi: "很远吗？", pinyin: "hěn yuǎn ma?", en: "is it far?", scenario: "directions", note: "" },
  { hanzi: "我迷路了", pinyin: "wǒ mílù le", en: "I'm lost", scenario: "directions", note: "" },

  // emergency
  { hanzi: "救命！", pinyin: "jiùmìng!", en: "help!", scenario: "emergency", note: "shout this in a real emergency" },
  { hanzi: "请帮我", pinyin: "qǐng bāng wǒ", en: "please help me", scenario: "emergency", note: "" },
  { hanzi: "我生病了", pinyin: "wǒ shēngbìng le", en: "I'm sick", scenario: "emergency", note: "" },
  { hanzi: "医院在哪儿？", pinyin: "yīyuàn zài nǎr?", en: "where's the hospital?", scenario: "emergency", note: "" },
  { hanzi: "请叫警察", pinyin: "qǐng jiào jǐngchá", en: "please call the police", scenario: "emergency", note: "" },
  { hanzi: "我的护照丢了", pinyin: "wǒ de hùzhào diū le", en: "I lost my passport", scenario: "emergency", note: "" },
  { hanzi: "请叫医生", pinyin: "qǐng jiào yīshēng", en: "please call a doctor", scenario: "emergency", note: "" },

  // money
  { hanzi: "多少钱一个？", pinyin: "duōshao qián yí gè?", en: "how much per one?", scenario: "money", note: "" },
  { hanzi: "我要换钱", pinyin: "wǒ yào huàn qián", en: "I want to exchange money", scenario: "money", note: "" },
  { hanzi: "银行在哪儿？", pinyin: "yínháng zài nǎr?", en: "where's the bank?", scenario: "money", note: "" },
  { hanzi: "有没有现金？", pinyin: "yǒu méiyǒu xiànjīn?", en: "do you have cash?", scenario: "money", note: "" },
  { hanzi: "这个多少钱？", pinyin: "zhège duōshao qián?", en: "how much is this?", scenario: "money", note: "" },
  { hanzi: "太贵了，便宜点儿吧", pinyin: "tài guì le, piányi diǎnr ba", en: "too expensive, cheaper please", scenario: "money", note: "吧 softens it into a friendly suggestion" },
  { hanzi: "给你钱", pinyin: "gěi nǐ qián", en: "here's your money", scenario: "money", note: "said while handing over payment" },

  // airport
  { hanzi: "护照在这儿", pinyin: "hùzhào zài zhèr", en: "here's my passport", scenario: "airport", note: "" },
  { hanzi: "我的行李在哪儿？", pinyin: "wǒ de xíngli zài nǎr?", en: "where's my luggage?", scenario: "airport", note: "" },
  { hanzi: "登机口在哪儿？", pinyin: "dēngjīkǒu zài nǎr?", en: "where's the boarding gate?", scenario: "airport", note: "" },
  { hanzi: "飞机几点起飞？", pinyin: "fēijī jǐ diǎn qǐfēi?", en: "what time does the plane take off?", scenario: "airport", note: "" },
  { hanzi: "我要登机牌", pinyin: "wǒ yào dēngjīpái", en: "I need a boarding pass", scenario: "airport", note: "" },
  { hanzi: "飞机晚点了吗？", pinyin: "fēijī wǎndiǎn le ma?", en: "is the flight delayed?", scenario: "airport", note: "" },
  { hanzi: "这是我的行李", pinyin: "zhè shì wǒ de xíngli", en: "this is my luggage", scenario: "airport", note: "" },

  // smalltalk
  { hanzi: "你叫什么名字？", pinyin: "nǐ jiào shénme míngzi?", en: "what's your name?", scenario: "smalltalk", note: "" },
  { hanzi: "我叫……", pinyin: "wǒ jiào ...", en: "my name is ...", scenario: "smalltalk", note: "" },
  { hanzi: "你是哪国人？", pinyin: "nǐ shì nǎ guó rén?", en: "where are you from?", scenario: "smalltalk", note: "literally: which country's person" },
  { hanzi: "我是美国人", pinyin: "wǒ shì měiguórén", en: "I'm American", scenario: "smalltalk", note: "swap the country name" },
  { hanzi: "你会说英语吗？", pinyin: "nǐ huì shuō yīngyǔ ma?", en: "do you speak English?", scenario: "smalltalk", note: "" },
  { hanzi: "认识你很高兴", pinyin: "rènshi nǐ hěn gāoxìng", en: "nice to meet you", scenario: "smalltalk", note: "" },
  { hanzi: "你今年多大？", pinyin: "nǐ jīnnián duō dà?", en: "how old are you?", scenario: "smalltalk", note: "casual; ask 您多大年纪 for elders" }
],

dialogues: [
  {
    title: "Ordering food",
    emoji: "🍜",
    turns: [
      { who: "A", hanzi: "你好，请给我菜单。", pinyin: "Nǐ hǎo, qǐng gěi wǒ càidān.", en: "Hello, please give me the menu." },
      { who: "B", hanzi: "好的，你要喝点什么？", pinyin: "Hǎo de, nǐ yào hē diǎn shénme?", en: "Sure, what would you like to drink?" },
      { who: "A", hanzi: "我要一杯茶。", pinyin: "Wǒ yào yì bēi chá.", en: "I'd like a cup of tea." },
      { who: "B", hanzi: "你要吃什么菜？", pinyin: "Nǐ yào chī shénme cài?", en: "What dish would you like to eat?" },
      { who: "A", hanzi: "我要米饭和菜。", pinyin: "Wǒ yào mǐfàn hé cài.", en: "I'd like rice and a dish." },
      { who: "B", hanzi: "好，请等一下。", pinyin: "Hǎo, qǐng děng yíxià.", en: "Okay, please wait a moment." },
      { who: "A", hanzi: "谢谢。", pinyin: "Xièxie.", en: "Thank you." },
      { who: "B", hanzi: "不客气。", pinyin: "Bú kèqi.", en: "You're welcome." }
    ]
  },
  {
    title: "Buying something",
    emoji: "🛍️",
    turns: [
      { who: "A", hanzi: "这个多少钱？", pinyin: "Zhège duōshao qián?", en: "How much is this?" },
      { who: "B", hanzi: "三十块。", pinyin: "Sānshí kuài.", en: "30 yuan." },
      { who: "A", hanzi: "太贵了，便宜一点儿吧。", pinyin: "Tài guì le, piányi yìdiǎnr ba.", en: "Too expensive, a bit cheaper please." },
      { who: "B", hanzi: "好，二十五块。", pinyin: "Hǎo, èrshíwǔ kuài.", en: "Okay, 25 yuan." },
      { who: "A", hanzi: "可以刷卡吗？", pinyin: "Kěyǐ shuākǎ ma?", en: "Can I pay by card?" },
      { who: "B", hanzi: "可以。", pinyin: "Kěyǐ.", en: "Yes, you can." },
      { who: "A", hanzi: "谢谢你。", pinyin: "Xièxie nǐ.", en: "Thank you." }
    ]
  },
  {
    title: "Taking a taxi",
    emoji: "🚕",
    turns: [
      { who: "A", hanzi: "我要去机场。", pinyin: "Wǒ yào qù jīchǎng.", en: "I want to go to the airport." },
      { who: "B", hanzi: "好的，上车吧。", pinyin: "Hǎo de, shàng chē ba.", en: "Okay, get in." },
      { who: "A", hanzi: "到机场要多久？", pinyin: "Dào jīchǎng yào duō jiǔ?", en: "How long to the airport?" },
      { who: "B", hanzi: "二十分钟。", pinyin: "Èrshí fēnzhōng.", en: "20 minutes." },
      { who: "A", hanzi: "请开慢一点儿。", pinyin: "Qǐng kāi màn yìdiǎnr.", en: "Please drive a bit slower." },
      { who: "B", hanzi: "好的。", pinyin: "Hǎo de.", en: "Okay." },
      { who: "A", hanzi: "多少钱？", pinyin: "Duōshao qián?", en: "How much is it?" },
      { who: "B", hanzi: "五十块。", pinyin: "Wǔshí kuài.", en: "50 yuan." }
    ]
  },
  {
    title: "Checking into a hotel",
    emoji: "🏨",
    turns: [
      { who: "A", hanzi: "你好，我订了一个房间。", pinyin: "Nǐ hǎo, wǒ dìng le yí gè fángjiān.", en: "Hello, I booked a room." },
      { who: "B", hanzi: "你叫什么名字？", pinyin: "Nǐ jiào shénme míngzi?", en: "What's your name?" },
      { who: "A", hanzi: "我叫王明。", pinyin: "Wǒ jiào Wáng Míng.", en: "My name is Wang Ming." },
      { who: "B", hanzi: "好，这是你的房间钥匙。", pinyin: "Hǎo, zhè shì nǐ de fángjiān yàoshi.", en: "Okay, here's your room key." },
      { who: "A", hanzi: "有没有网络？", pinyin: "Yǒu méiyǒu wǎngluò?", en: "Is there wifi?" },
      { who: "B", hanzi: "有，密码在这儿。", pinyin: "Yǒu, mìmǎ zài zhèr.", en: "Yes, the password is here." },
      { who: "A", hanzi: "谢谢。", pinyin: "Xièxie.", en: "Thank you." }
    ]
  },
  {
    title: "Asking directions",
    emoji: "🗺️",
    turns: [
      { who: "A", hanzi: "请问，洗手间在哪儿？", pinyin: "Qǐngwèn, xǐshǒujiān zài nǎr?", en: "Excuse me, where's the restroom?" },
      { who: "B", hanzi: "一直走，在右边。", pinyin: "Yìzhí zǒu, zài yòubiān.", en: "Go straight, it's on the right." },
      { who: "A", hanzi: "很远吗？", pinyin: "Hěn yuǎn ma?", en: "Is it far?" },
      { who: "B", hanzi: "不远，很近。", pinyin: "Bù yuǎn, hěn jìn.", en: "Not far, very close." },
      { who: "A", hanzi: "谢谢你。", pinyin: "Xièxie nǐ.", en: "Thank you." },
      { who: "B", hanzi: "不客气。", pinyin: "Bú kèqi.", en: "You're welcome." }
    ]
  },
  {
    title: "Meeting someone",
    emoji: "👋",
    turns: [
      { who: "A", hanzi: "你好，我叫李红。", pinyin: "Nǐ hǎo, wǒ jiào Lǐ Hóng.", en: "Hello, my name is Li Hong." },
      { who: "B", hanzi: "你好，我叫大卫。认识你很高兴。", pinyin: "Nǐ hǎo, wǒ jiào Dàwèi. Rènshi nǐ hěn gāoxìng.", en: "Hello, my name is David. Nice to meet you." },
      { who: "A", hanzi: "你是哪国人？", pinyin: "Nǐ shì nǎ guó rén?", en: "Where are you from?" },
      { who: "B", hanzi: "我是美国人。你呢？", pinyin: "Wǒ shì měiguórén. Nǐ ne?", en: "I'm American. And you?" },
      { who: "A", hanzi: "我是中国人。", pinyin: "Wǒ shì Zhōngguórén.", en: "I'm Chinese." },
      { who: "B", hanzi: "你会说英语吗？", pinyin: "Nǐ huì shuō yīngyǔ ma?", en: "Do you speak English?" },
      { who: "A", hanzi: "会一点儿。", pinyin: "Huì yìdiǎnr.", en: "A little." }
    ]
  },
  {
    title: "At a cafe",
    emoji: "☕",
    turns: [
      { who: "A", hanzi: "你好，我要一杯咖啡。", pinyin: "Nǐ hǎo, wǒ yào yì bēi kāfēi.", en: "Hello, I'd like a cup of coffee." },
      { who: "B", hanzi: "好的，热的还是冷的？", pinyin: "Hǎo de, rè de háishi lěng de?", en: "Okay, hot or cold?" },
      { who: "A", hanzi: "热的，谢谢。", pinyin: "Rè de, xièxie.", en: "Hot, thanks." },
      { who: "B", hanzi: "还要别的吗？", pinyin: "Hái yào bié de ma?", en: "Anything else?" },
      { who: "A", hanzi: "不要了，谢谢。", pinyin: "Bú yào le, xièxie.", en: "No, thank you." },
      { who: "B", hanzi: "好，请等一下。", pinyin: "Hǎo, qǐng děng yíxià.", en: "Okay, please wait a moment." }
    ]
  },
  {
    title: "Asking for help",
    emoji: "🆘",
    turns: [
      { who: "A", hanzi: "对不起，请帮我。", pinyin: "Duìbuqǐ, qǐng bāng wǒ.", en: "Excuse me, please help me." },
      { who: "B", hanzi: "怎么了？", pinyin: "Zěnme le?", en: "What's wrong?" },
      { who: "A", hanzi: "我的护照丢了。", pinyin: "Wǒ de hùzhào diū le.", en: "I lost my passport." },
      { who: "B", hanzi: "我们去警察那儿。", pinyin: "Wǒmen qù jǐngchá nàr.", en: "Let's go to the police." },
      { who: "A", hanzi: "好，谢谢你。", pinyin: "Hǎo, xièxie nǐ.", en: "Okay, thank you." },
      { who: "B", hanzi: "不客气。", pinyin: "Bú kèqi.", en: "You're welcome." }
    ]
  }
]

};

window.YAHA_DATA.tones = [
  { tone: 1, mark: "ā", desc: "high and flat, held steady", example: { hanzi: "妈", pinyin: "mā", en: "mom" } },
  { tone: 2, mark: "á", desc: "rising, like asking \"what?\"", example: { hanzi: "麻", pinyin: "má", en: "hemp, numb" } },
  { tone: 3, mark: "ǎ", desc: "dips down then rises", example: { hanzi: "马", pinyin: "mǎ", en: "horse" } },
  { tone: 4, mark: "à", desc: "sharp fall, like a firm command", example: { hanzi: "骂", pinyin: "mà", en: "to scold" } },
  { tone: 0, mark: "a", desc: "neutral — light and short, no stress", example: { hanzi: "吗", pinyin: "ma", en: "question particle" } }
];
