/* YaHa — HSK2 vocabulary (classic 150-word HSK level 2 list, old HSK words 151-300).
   Excludes all HSK1 words (those live in data.js). 虽然…但是… and 因为…所以… are split
   into their four component conjunctions, matching the official 2012 word file.
   Plain script (no modules). Assigns window.YAHA_HSK2.
   Cross-checked against hsk.academy and the official 2012 list (hskhsk.com data). */

window.YAHA_HSK2 = [
  { hanzi: "吧", pinyin: "ba", en: "suggestion particle (let's...)", pos: "particle", cat: "grammar" },
  { hanzi: "白", pinyin: "bái", en: "white", pos: "adj", cat: "colors" },
  { hanzi: "百", pinyin: "bǎi", en: "hundred", pos: "num", cat: "numbers" },
  { hanzi: "帮助", pinyin: "bāngzhù", en: "to help", pos: "v", cat: "verbs" },
  { hanzi: "报纸", pinyin: "bàozhǐ", en: "newspaper", pos: "n", cat: "objects" },
  { hanzi: "比", pinyin: "bǐ", en: "than; to compare", pos: "prep", cat: "grammar" },
  { hanzi: "别", pinyin: "bié", en: "don't", pos: "adv", cat: "grammar" },
  { hanzi: "宾馆", pinyin: "bīnguǎn", en: "hotel, guesthouse", pos: "n", cat: "travel" },
  { hanzi: "长", pinyin: "cháng", en: "long", pos: "adj", cat: "adjectives" },
  { hanzi: "唱歌", pinyin: "chànggē", en: "to sing (a song)", pos: "v", cat: "activities" },
  { hanzi: "出", pinyin: "chū", en: "to go out, to come out", pos: "v", cat: "verbs" },
  { hanzi: "穿", pinyin: "chuān", en: "to wear, to put on", pos: "v", cat: "verbs" },
  { hanzi: "次", pinyin: "cì", en: "time (occurrence)", pos: "measure", cat: "measure" },
  { hanzi: "从", pinyin: "cóng", en: "from", pos: "prep", cat: "grammar" },
  { hanzi: "错", pinyin: "cuò", en: "wrong; mistake", pos: "adj", cat: "adjectives" },
  { hanzi: "打篮球", pinyin: "dǎ lánqiú", en: "to play basketball", pos: "v", cat: "activities" },
  { hanzi: "大家", pinyin: "dàjiā", en: "everyone", pos: "pron", cat: "people" },
  { hanzi: "到", pinyin: "dào", en: "to arrive; to, until", pos: "v", cat: "verbs" },
  { hanzi: "得", pinyin: "de", en: "degree particle (verb + de + how)", pos: "particle", cat: "grammar" },
  { hanzi: "等", pinyin: "děng", en: "to wait", pos: "v", cat: "verbs" },
  { hanzi: "弟弟", pinyin: "dìdi", en: "younger brother", pos: "n", cat: "people" },
  { hanzi: "第一", pinyin: "dì yī", en: "first", pos: "num", cat: "numbers" },
  { hanzi: "懂", pinyin: "dǒng", en: "to understand", pos: "v", cat: "verbs" },
  { hanzi: "对", pinyin: "duì", en: "correct, right; toward", pos: "adj", cat: "adjectives" },
  { hanzi: "房间", pinyin: "fángjiān", en: "room", pos: "n", cat: "places" },
  { hanzi: "非常", pinyin: "fēicháng", en: "very, extremely", pos: "adv", cat: "grammar" },
  { hanzi: "服务员", pinyin: "fúwùyuán", en: "waiter, attendant", pos: "n", cat: "people" },
  { hanzi: "高", pinyin: "gāo", en: "tall, high", pos: "adj", cat: "adjectives" },
  { hanzi: "告诉", pinyin: "gàosu", en: "to tell", pos: "v", cat: "verbs" },
  { hanzi: "哥哥", pinyin: "gēge", en: "older brother", pos: "n", cat: "people" },
  { hanzi: "给", pinyin: "gěi", en: "to give; for, to", pos: "v", cat: "verbs" },
  { hanzi: "公共汽车", pinyin: "gōnggòng qìchē", en: "public bus", pos: "n", cat: "travel" },
  { hanzi: "公司", pinyin: "gōngsī", en: "company", pos: "n", cat: "places" },
  { hanzi: "贵", pinyin: "guì", en: "expensive", pos: "adj", cat: "adjectives" },
  { hanzi: "过", pinyin: "guo", en: "experience particle (have done before)", pos: "particle", cat: "grammar" },
  { hanzi: "还", pinyin: "hái", en: "still, also", pos: "adv", cat: "grammar" },
  { hanzi: "孩子", pinyin: "háizi", en: "child", pos: "n", cat: "people" },
  { hanzi: "好吃", pinyin: "hǎochī", en: "delicious, tasty", pos: "adj", cat: "food" },
  { hanzi: "黑", pinyin: "hēi", en: "black; dark", pos: "adj", cat: "colors" },
  { hanzi: "红", pinyin: "hóng", en: "red", pos: "adj", cat: "colors" },
  { hanzi: "火车站", pinyin: "huǒchēzhàn", en: "train station", pos: "n", cat: "travel" },
  { hanzi: "机场", pinyin: "jīchǎng", en: "airport", pos: "n", cat: "travel" },
  { hanzi: "鸡蛋", pinyin: "jīdàn", en: "egg", pos: "n", cat: "food" },
  { hanzi: "件", pinyin: "jiàn", en: "measure word (clothes, matters)", pos: "measure", cat: "measure" },
  { hanzi: "教室", pinyin: "jiàoshì", en: "classroom", pos: "n", cat: "places" },
  { hanzi: "姐姐", pinyin: "jiějie", en: "older sister", pos: "n", cat: "people" },
  { hanzi: "介绍", pinyin: "jièshào", en: "to introduce", pos: "v", cat: "verbs" },
  { hanzi: "进", pinyin: "jìn", en: "to enter", pos: "v", cat: "verbs" },
  { hanzi: "近", pinyin: "jìn", en: "near, close", pos: "adj", cat: "adjectives" },
  { hanzi: "就", pinyin: "jiù", en: "then, right away; just", pos: "adv", cat: "grammar" },
  { hanzi: "觉得", pinyin: "juéde", en: "to feel, to think", pos: "v", cat: "verbs" },
  { hanzi: "咖啡", pinyin: "kāfēi", en: "coffee", pos: "n", cat: "food" },
  { hanzi: "开始", pinyin: "kāishǐ", en: "to begin, to start", pos: "v", cat: "verbs" },
  { hanzi: "考试", pinyin: "kǎoshì", en: "exam, test", pos: "n", cat: "activities" },
  { hanzi: "可能", pinyin: "kěnéng", en: "maybe, possible", pos: "adv", cat: "grammar" },
  { hanzi: "可以", pinyin: "kěyǐ", en: "can, may", pos: "v", cat: "grammar" },
  { hanzi: "课", pinyin: "kè", en: "class, lesson", pos: "n", cat: "activities" },
  { hanzi: "快", pinyin: "kuài", en: "fast, quick; soon", pos: "adj", cat: "adjectives" },
  { hanzi: "快乐", pinyin: "kuàilè", en: "happy", pos: "adj", cat: "adjectives" },
  { hanzi: "累", pinyin: "lèi", en: "tired", pos: "adj", cat: "adjectives" },
  { hanzi: "离", pinyin: "lí", en: "away from (distance)", pos: "prep", cat: "grammar" },
  { hanzi: "两", pinyin: "liǎng", en: "two (before measure words)", pos: "num", cat: "numbers" },
  { hanzi: "零", pinyin: "líng", en: "zero", pos: "num", cat: "numbers" },
  { hanzi: "路", pinyin: "lù", en: "road, route", pos: "n", cat: "travel" },
  { hanzi: "旅游", pinyin: "lǚyóu", en: "to travel, to tour", pos: "v", cat: "travel" },
  { hanzi: "卖", pinyin: "mài", en: "to sell", pos: "v", cat: "verbs" },
  { hanzi: "慢", pinyin: "màn", en: "slow", pos: "adj", cat: "adjectives" },
  { hanzi: "忙", pinyin: "máng", en: "busy", pos: "adj", cat: "adjectives" },
  { hanzi: "每", pinyin: "měi", en: "every, each", pos: "pron", cat: "grammar" },
  { hanzi: "妹妹", pinyin: "mèimei", en: "younger sister", pos: "n", cat: "people" },
  { hanzi: "门", pinyin: "mén", en: "door, gate", pos: "n", cat: "objects" },
  { hanzi: "面条", pinyin: "miàntiáo", en: "noodles", pos: "n", cat: "food" },
  { hanzi: "男", pinyin: "nán", en: "male, man", pos: "adj", cat: "people" },
  { hanzi: "您", pinyin: "nín", en: "you (polite)", pos: "pron", cat: "people" },
  { hanzi: "牛奶", pinyin: "niúnǎi", en: "milk", pos: "n", cat: "food" },
  { hanzi: "女", pinyin: "nǚ", en: "female, woman", pos: "adj", cat: "people" },
  { hanzi: "旁边", pinyin: "pángbiān", en: "beside, next to", pos: "n", cat: "places" },
  { hanzi: "跑步", pinyin: "pǎobù", en: "to run, to jog", pos: "v", cat: "activities" },
  { hanzi: "便宜", pinyin: "piányi", en: "cheap", pos: "adj", cat: "adjectives" },
  { hanzi: "票", pinyin: "piào", en: "ticket", pos: "n", cat: "travel" },
  { hanzi: "妻子", pinyin: "qīzi", en: "wife", pos: "n", cat: "people" },
  { hanzi: "起床", pinyin: "qǐchuáng", en: "to get up (out of bed)", pos: "v", cat: "activities" },
  { hanzi: "千", pinyin: "qiān", en: "thousand", pos: "num", cat: "numbers" },
  { hanzi: "铅笔", pinyin: "qiānbǐ", en: "pencil", pos: "n", cat: "objects" },
  { hanzi: "晴", pinyin: "qíng", en: "sunny, clear", pos: "adj", cat: "weather" },
  { hanzi: "去年", pinyin: "qùnián", en: "last year", pos: "time", cat: "time" },
  { hanzi: "让", pinyin: "ràng", en: "to let, to allow", pos: "v", cat: "verbs" },
  { hanzi: "日", pinyin: "rì", en: "day; date", pos: "time", cat: "time" },
  { hanzi: "上班", pinyin: "shàngbān", en: "to go to work", pos: "v", cat: "activities" },
  { hanzi: "身体", pinyin: "shēntǐ", en: "body; health", pos: "n", cat: "body" },
  { hanzi: "生病", pinyin: "shēngbìng", en: "to get sick", pos: "v", cat: "body" },
  { hanzi: "生日", pinyin: "shēngrì", en: "birthday", pos: "n", cat: "time" },
  { hanzi: "时间", pinyin: "shíjiān", en: "time", pos: "n", cat: "time" },
  { hanzi: "事情", pinyin: "shìqing", en: "matter, thing, affair", pos: "n", cat: "objects" },
  { hanzi: "手表", pinyin: "shǒubiǎo", en: "wristwatch", pos: "n", cat: "objects" },
  { hanzi: "手机", pinyin: "shǒujī", en: "cell phone", pos: "n", cat: "objects" },
  { hanzi: "说话", pinyin: "shuōhuà", en: "to speak, to talk", pos: "v", cat: "verbs" },
  { hanzi: "送", pinyin: "sòng", en: "to give (a gift); to see off, to deliver", pos: "v", cat: "verbs" },
  { hanzi: "虽然", pinyin: "suīrán", en: "although (虽然…但是…)", pos: "conj", cat: "grammar" },
  { hanzi: "但是", pinyin: "dànshì", en: "but, however", pos: "conj", cat: "grammar" },
  { hanzi: "它", pinyin: "tā", en: "it (animals, things)", pos: "pron", cat: "grammar" },
  { hanzi: "踢足球", pinyin: "tī zúqiú", en: "to play soccer", pos: "v", cat: "activities" },
  { hanzi: "题", pinyin: "tí", en: "question, exam problem", pos: "n", cat: "objects" },
  { hanzi: "跳舞", pinyin: "tiàowǔ", en: "to dance", pos: "v", cat: "activities" },
  { hanzi: "外", pinyin: "wài", en: "outside", pos: "n", cat: "places" },
  { hanzi: "完", pinyin: "wán", en: "to finish, to be done", pos: "v", cat: "verbs" },
  { hanzi: "玩", pinyin: "wán", en: "to play, to have fun", pos: "v", cat: "activities" },
  { hanzi: "晚上", pinyin: "wǎnshang", en: "evening, night", pos: "time", cat: "time" },
  { hanzi: "往", pinyin: "wǎng", en: "toward, to", pos: "prep", cat: "grammar" },
  { hanzi: "为什么", pinyin: "wèishénme", en: "why", pos: "question", cat: "question" },
  { hanzi: "问", pinyin: "wèn", en: "to ask", pos: "v", cat: "verbs" },
  { hanzi: "问题", pinyin: "wèntí", en: "question, problem", pos: "n", cat: "question" },
  { hanzi: "西瓜", pinyin: "xīguā", en: "watermelon", pos: "n", cat: "food" },
  { hanzi: "希望", pinyin: "xīwàng", en: "to hope, to wish", pos: "v", cat: "verbs" },
  { hanzi: "洗", pinyin: "xǐ", en: "to wash", pos: "v", cat: "verbs" },
  { hanzi: "小时", pinyin: "xiǎoshí", en: "hour", pos: "n", cat: "time" },
  { hanzi: "笑", pinyin: "xiào", en: "to laugh, to smile", pos: "v", cat: "verbs" },
  { hanzi: "新", pinyin: "xīn", en: "new", pos: "adj", cat: "adjectives" },
  { hanzi: "姓", pinyin: "xìng", en: "surname; to be surnamed", pos: "v", cat: "people" },
  { hanzi: "休息", pinyin: "xiūxi", en: "to rest", pos: "v", cat: "activities" },
  { hanzi: "雪", pinyin: "xuě", en: "snow", pos: "n", cat: "weather" },
  { hanzi: "颜色", pinyin: "yánsè", en: "color", pos: "n", cat: "colors" },
  { hanzi: "眼睛", pinyin: "yǎnjing", en: "eye", pos: "n", cat: "body" },
  { hanzi: "羊肉", pinyin: "yángròu", en: "mutton, lamb", pos: "n", cat: "food" },
  { hanzi: "药", pinyin: "yào", en: "medicine", pos: "n", cat: "body" },
  { hanzi: "要", pinyin: "yào", en: "to want; will, must", pos: "v", cat: "verbs" },
  { hanzi: "也", pinyin: "yě", en: "also, too", pos: "adv", cat: "grammar" },
  { hanzi: "一起", pinyin: "yīqǐ", en: "together", pos: "adv", cat: "grammar" },
  { hanzi: "一下", pinyin: "yīxià", en: "a bit, briefly (verb + yixia)", pos: "adv", cat: "grammar" },
  { hanzi: "已经", pinyin: "yǐjīng", en: "already", pos: "adv", cat: "grammar" },
  { hanzi: "意思", pinyin: "yìsi", en: "meaning", pos: "n", cat: "grammar" },
  { hanzi: "因为", pinyin: "yīnwèi", en: "because (因为…所以…)", pos: "conj", cat: "grammar" },
  { hanzi: "所以", pinyin: "suǒyǐ", en: "so, therefore", pos: "conj", cat: "grammar" },
  { hanzi: "阴", pinyin: "yīn", en: "cloudy, overcast", pos: "adj", cat: "weather" },
  { hanzi: "游泳", pinyin: "yóuyǒng", en: "to swim", pos: "v", cat: "activities" },
  { hanzi: "右边", pinyin: "yòubian", en: "right side", pos: "n", cat: "places" },
  { hanzi: "鱼", pinyin: "yú", en: "fish", pos: "n", cat: "food" },
  { hanzi: "远", pinyin: "yuǎn", en: "far", pos: "adj", cat: "adjectives" },
  { hanzi: "运动", pinyin: "yùndòng", en: "sports, exercise", pos: "n", cat: "activities" },
  { hanzi: "再", pinyin: "zài", en: "again, once more", pos: "adv", cat: "grammar" },
  { hanzi: "早上", pinyin: "zǎoshang", en: "(early) morning", pos: "time", cat: "time" },
  { hanzi: "丈夫", pinyin: "zhàngfu", en: "husband", pos: "n", cat: "people" },
  { hanzi: "找", pinyin: "zhǎo", en: "to look for, to find", pos: "v", cat: "verbs" },
  { hanzi: "着", pinyin: "zhe", en: "ongoing-action particle (-ing)", pos: "particle", cat: "grammar" },
  { hanzi: "真", pinyin: "zhēn", en: "really, truly", pos: "adv", cat: "grammar" },
  { hanzi: "正在", pinyin: "zhèngzài", en: "in the middle of (doing)", pos: "adv", cat: "grammar" },
  { hanzi: "知道", pinyin: "zhīdào", en: "to know", pos: "v", cat: "verbs" },
  { hanzi: "准备", pinyin: "zhǔnbèi", en: "to prepare", pos: "v", cat: "verbs" },
  { hanzi: "走", pinyin: "zǒu", en: "to walk, to go", pos: "v", cat: "verbs" },
  { hanzi: "最", pinyin: "zuì", en: "most, -est", pos: "adv", cat: "grammar" },
  { hanzi: "左边", pinyin: "zuǒbian", en: "left side", pos: "n", cat: "places" }
];
